services:
  db:
    image: postgres:15-alpine
    container_name: johnson_db
    environment:
      - POSTGRES_DB=johnsondb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Johnsonbase2026
    ports:
      - "5433:5432" # <--- Windows entra por el 5433, pero Docker usa el 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U admin -d johnsondb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Dentro de Docker, la comunicaciÃ³n es directa al 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/johnsondb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Johnsonbase2026
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    restart: on-failure

volumes:
  postgres_data: